[server]
headless = true
port = 8000
enableCORS = false

[theme]
base = "light"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8000

[client]
showSidebarNavigation = false

[global]
favicon = "favicon.png"
